### ISSUE TITLE
composer-fork/composer no longer supported

### ISSUE THREAD

**Issue by o-rel** [symfony-bundle/jquery-bundle#1]
Hello,

I just installed this bundle and it seems it's using composer-fork/composer which is not supported anymore, and precognize to use composer/composer (current version 1.0.0-alpha11).

**Comment by amouhzi** [comment]
Hello,

This package is not supported anymore.

It is not a best practice to use a bundle to download Jquery, use Bower or somthing similar instead.

Thanks.

**Comment by o-rel** [comment]
Thank you, I'll take a look on bower.

Thanks.
